import { FileText, Sparkles, RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useState } from 'react';

const NarrativeSummary = () => {
  const [isGenerating, setIsGenerating] = useState(false);

  const narrativeText = `The CCTV footage captured at the main entrance reveals a sequence of concerning activities over a 5-minute period. At 00:00, an individual was detected entering the building through the main entrance. The subject exhibited loitering behavior near the entrance area at approximately 00:45, remaining stationary for an extended period.

At 02:10, the AI system detected an unauthorized access attempt when the individual approached a restricted zone. The LSTM-based activity recognition module identified suspicious movement patterns consistent with intrusion behavior.

A critical incident occurred at 03:00 when the system detected theft activity - an object was removed from the monitored area without authorization. The individual subsequently exited the building at 04:30.

The combined analysis of YOLO object detection and LSTM temporal modeling indicates a pre-planned security breach with high confidence.`;

  const labels = ['Entry', 'Loitering', 'Intrusion', 'Theft', 'Exit'];

  const handleRegenerate = () => {
    setIsGenerating(true);
    setTimeout(() => setIsGenerating(false), 2000);
  };

  return (
    <div className="glass-card p-4 h-full flex flex-col">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <div className="p-2 bg-primary/20 rounded-lg">
            <Sparkles className="w-5 h-5 text-primary" />
          </div>
          <div>
            <h3 className="font-semibold">AI Narrative Summary</h3>
            <p className="text-xs text-muted-foreground">Generated by LLM</p>
          </div>
        </div>
        <Button
          variant="ghost"
          size="sm"
          onClick={handleRegenerate}
          disabled={isGenerating}
          className="gap-2"
        >
          <RefreshCw className={`w-4 h-4 ${isGenerating ? 'animate-spin' : ''}`} />
          Regenerate
        </Button>
      </div>

      {/* Generated Labels */}
      <div className="mb-4">
        <p className="text-xs text-muted-foreground mb-2">Detected Activity Labels:</p>
        <div className="flex flex-wrap gap-2">
          {labels.map((label, index) => (
            <span
              key={label}
              className="text-xs px-3 py-1 bg-secondary rounded-full font-medium animate-slide-up"
              style={{ animationDelay: `${index * 50}ms` }}
            >
              {label}
            </span>
          ))}
        </div>
      </div>

      {/* Narrative Text */}
      <div className="flex-1 overflow-y-auto scrollbar-thin">
        <div className="prose prose-sm prose-invert max-w-none">
          {isGenerating ? (
            <div className="space-y-2">
              <div className="h-4 bg-secondary rounded animate-pulse w-full" />
              <div className="h-4 bg-secondary rounded animate-pulse w-[95%]" />
              <div className="h-4 bg-secondary rounded animate-pulse w-[90%]" />
              <div className="h-4 bg-secondary rounded animate-pulse w-full" />
              <div className="h-4 bg-secondary rounded animate-pulse w-[85%]" />
            </div>
          ) : (
            <p className="text-sm text-muted-foreground leading-relaxed whitespace-pre-line">
              {narrativeText}
            </p>
          )}
        </div>
      </div>

      {/* LLM Badge */}
      <div className="mt-4 pt-3 border-t border-border/50 flex items-center justify-between">
        <div className="flex items-center gap-2 text-xs text-muted-foreground">
          <FileText className="w-4 h-4" />
          <span>345 words • Generated in 1.2s</span>
        </div>
        <span className="text-xs bg-primary/20 text-primary px-2 py-1 rounded-full font-mono">
          GPT-4 Vision
        </span>
      </div>
    </div>
  );
};

export default NarrativeSummary;
